name: CI - Mveledziso

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:

  backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BackEnd/Mveledziso/10.0.1/aspnet-core

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.202'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"


  # frontend:
  #   name: Build & Lint Frontend
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./Frontend

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: List files in Frontend directory
  #       run: |
  #         echo "Current directory: $(pwd)"
  #         ls -al

  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '18'
  #         cache: 'npm'
  #         cache-dependency-path: ./Frontend/package-lock.json

  #     - name: Display Node.js and npm versions
  #       run: |
  #         echo "Node.js version: $(node --version)"
  #         echo "npm version: $(npm --version)"

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Build project
  #       run: npm run build

  #     - name: Run linting
  #       run: npm run lint
